### ISSUE TITLE
This policy contains the following error: Has prohibited field Principal For more information about the IAM policy grammar,

### ISSUE THREAD

**Issue by Zyles** [arithmetric/aws-lambda-ses-forwarder#106]
The policy on the tutorial does not work.

```
{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Sid": "GiveSESPermissionToWriteEmail",
         "Effect": "Allow",
         "Principal": {
            "Service": "ses.amazonaws.com"
         },
         "Action": "s3:PutObject",
         "Resource": "arn:aws:s3:::S3-BUCKET-NAME/*",
         "Condition": {
            "StringEquals": {
               "aws:Referer": "AWS-ACCOUNT-ID"
            }
         }
      }
   ]
}
```

**Comment by zmingxie** [comment]
You need to update the following 2 lines to match your own account setup:
```
 "Resource": "arn:aws:s3:::S3-BUCKET-NAME/*",
```
and
```
"aws:Referer": "AWS-ACCOUNT-ID"
```

**Comment by Zyles** [comment]
I did, that is not the problem.

**Comment by zmingxie** [comment]
Which AWS region are you trying this from?

**Comment by bmizepatterson** [comment]
I'm also having issues with the S3 bucket policy given in the docs. My SES rules successfully write incoming mail to the bucket, but the lambda function gets an 'Access Denied' error when trying to fetch it. The policy given appears to grant PutObject access to SES. Doesn't Lambda need GetObject access as well?

### Further Reading:
[Specifying a Principal](https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-bucket-user-policy-specifying-principal-intro.html)
[AWS JSON Policy Elements: Principal](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html)
[AWS Services That Work with IAM](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html)
[AWS Lambda Permissions](https://docs.aws.amazon.com/lambda/latest/dg/lambda-permissions.html)

**Comment by bmizepatterson** [comment]
Nevermind! In my case the 403 Access Denied error was masking a 404 Not Found. Turns out I had a typo in my config that had it searching the wrong key prefix.

Since the Lambda role doesn't grant ListBucket access, S3 returns a 403 instead of a 404 when it the object it's requesting isn't found.

Regarding permissions: I realize now that GetObject access is granted to the Lambda function within the IAM role assigned to it, so it's not necessary to duplicate that grant within the S3 bucket policy.

**Comment by Zyles** [comment]
Got it to work.

**Comment by planetahuevo** [comment]
Can someone explain how you sort this out? I am having the same issue.
Thanks
