### ISSUE TITLE
Node.js version 8.10 deprecated

### ISSUE THREAD

**Issue by dubrowin** [arithmetric/aws-lambda-ses-forwarder#107]
I see in the Node.js Working Group (https://github.com/nodejs/Release) that Node.js 8.x will be end of life at the end of Dec 2019. Is there plans to port to a newer version of Node for this function?

**Comment by tlaughlin1969** [comment]
It seems to work fine under Node 10 and package.json is not preventing higher versions of node.  May just be a case of updating the documentation.

**Comment by SeriousMatt** [comment]
Also seems to work with 12.x

**Comment by arithmetric** [comment]
Thanks for the report. I've updated the documentation and tests to show compatibility with Node.js 10.x and 12.x.
