### ISSUE TITLE
Thank you for this!

### ISSUE THREAD

**Issue by denitsa-cm** [arithmetric/aws-lambda-ses-forwarder#116]
It just works! With attachments and all! 

Big thank you - I've been looking into forwarding emails and it seemed like a daunting task to do with ses. Is there any way I can donate? :)

**Comment by cesarbarone** [comment]
@arithmetric thanks too. You saved my life!

**Comment by arithmetric** [comment]
Thanks very much for the feedback! I'll consider a way to donate or sponsor in the future.
