### ISSUE TITLE
Unable to import module 'index'

### ISSUE THREAD

**Issue by RdL87** [arithmetric/aws-lambda-ses-forwarder#117]
Hi, 

i always encounter this error when i trigger the function sending an email to the configured address.

`Unable to import module 'index': Error
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)`

**Comment by quaeritate** [comment]
The file isn't call module.js

It is index.js and the handler should be filename.function which in this case is index.handler

Does that help?

**Comment by arithmetric** [comment]
Hi @RdL87, we would need more information on how you are using the script to help out. I'm closing this issue until it is clear on how to reproduce it.
