### ISSUE TITLE
Followed the guide, only AMAZON_SES_SETUP_NOTIFICATION shows in bucket

### ISSUE THREAD

**Issue by idomic** [arithmetric/aws-lambda-ses-forwarder#143]
So the only thing I see is that some item `AMAZON_SES_SETUP_NOTIFICATION`, shows in the bucket.
The lambda isn't triggering, I keep emailing to the contact@email without success. Any idea what's going on?

I did test the lambda function, I've used `index.js` with node V 16, it does run on the test event (but fails since I don't have the format).
When emailing to it from my gmail I `530 Authentication required`

**Comment by adamb924** [comment]
It would be good to have the documentation updated before closing this..
