### ISSUE TITLE
key matching for the forwardMapping config variable is case sensitive

### ISSUE THREAD

**Issue by raphK** [arithmetric/aws-lambda-ses-forwarder#24]
As the code currently stands emails sent to inFo@example.com won't be forwarded to example.john@example.com and example.jen@example.com

I managed to alter the code to get it working but I've never submitted code to github, nor am I particularly proficient at JavaScript so I'll raise this issue and leave it to someone more competent to fix.

FYI - i used the .tolowercase() function in lines 66,68 and 69

**Comment by arithmetric** [comment]
@raphK Thanks for the report! I'm testing a fix for this issue.
