### ISSUE TITLE
Support SES receive action

### ISSUE THREAD

**Issue by iBobik** [arithmetric/aws-lambda-ses-forwarder#3]
Currently it depends on storing incoming e-mails to S3. Why it don't fetch e-mails from event, so we don't need S3?

**Comment by jakubboucek** [comment]
Because only S3 method allow has bigger limit than 150kb to message. See: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/limits.html

**Comment by jakubboucek** [comment]
Or better source: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-action-sns.html

**Comment by iBobik** [comment]
Thanks :-)
