### ISSUE TITLE
Error 'Authorization Mechanism (...) not supported. Please use AWS4-HMAC-SHA256'

### ISSUE THREAD

**Issue by sumtxt** [arithmetric/aws-lambda-ses-forwarder#39]
Function might fail if S3 bucket [is stored in a EU region](https://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4). CloudWatch will record an error saying "Please use AWS4-HMAC-SHA256' you need to use Signature Version 4 when initializing the conntection to the S3 bucket". Can be easily fixed by changing line 275 from AWS.S3() to AWS.S3({signatureVersion: 'v4'}).

**Comment by BenSower** [comment]
Can confirm the problem as well as the fix.
Until this is fixed, you can also directly update the AWS Object in your code:
`AWS.config.update({ signatureVersion: 'v4' })`

**Comment by arithmetric** [comment]
Thanks for the report @sumtxt and confirmation @BenSower.

I created PR #47 with the change that I think you're suggesting. Could you confirm if this fixes the issue for you?

**Comment by sumtxt** [comment]
Thanks! Works for me.
