### ISSUE TITLE
Problems identifying original sender

### ISSUE THREAD

**Issue by nickj69** [arithmetric/aws-lambda-ses-forwarder#43]
Got it all set up nicely for multiple domains, just have one issue. 

Some clients (Gmail) are showing messages up as from myself.
I think I have it configured correctly but suspect it is DKIM signing.
Because we're processing the email and using SES to send it on, it's being signed by my AWS identity. 

Any way to stop this? 

I presume the original mail is being signed by the original sender, but it will be stripped out when SES downloads it to the S3 bucket? 

e.g. 
From line says: "Other person at other.person@something.com < myemail@my.domain.com > "
Reply-to : "other.person@something.com <other.person@something.com>"
Signed-by: my.domain.com

**Comment by jakubboucek** [comment]
Gmail (and similar clients) use sophisticated algoritm to descript senders and can rewrite sent sender name. I recommend do not use known e-mail as `from` in redirected e-mail.

**Example of bad use:**
```javascript
var defaultConfig = {
  fromEmail: "jakub@boucek.info", //here is problem - do not use your e-mail 
  forwardMapping: {
    "info@mydomain.com": [
      "jakub@boucek.info"
    ]
  }
};
```

Better is use in `fromEmail` any unused e-mail, like a **noreply**@yourdomain.com

**Better example:**
```javascript
var defaultConfig = {
  fromEmail: "noreply@boucek.info", //use noreply@
  forwardMapping: {
    "info@mydomain.com": [
      "jakub@boucek.info"
    ]
  }
};
```

**Comment by nickj69** [comment]
Currently I have fromEmail blank. 

If I set fromEmail to my mail address, Gmail says it's from me outright, i.e. "Me at myemail@my.domain.com  < myemail@my.domain.com > "

If I set fromEmail to blank, Gmail says : "Other person at other.person@something.com < myemail@my.domain.com > "

Note the part in angular brackets. Hence why I think it is the DKIM signing. 
Note formatting in the original post dropped the angled brackets, I just updated.

**Comment by jakubboucek** [comment]
Oh, I see. Your first case is completed by Gmail (`Me`), second case is intentional feature of this script whet it [process a message](https://github.com/arithmetric/aws-lambda-ses-forwarder/blob/master/index.js#L212). 

A I said: I recommend in `fromEmail` use any unused e-mail, like a `noreply@yourdomain.com`.

**Comment by nickj69** [comment]
Aha. Thank you very much for the explanation. I missed the relevant bit of script.
