### ISSUE TITLE
InvalidParameterValue: Extra route-addr

### ISSUE THREAD

**Issue by ulsa2** [arithmetric/aws-lambda-ses-forwarder#48]
I get `InvalidParameterValue: Extra route-addr` when forwarding an email. Not sure what causes this, but I noticed that the email that fails has `charset=windows-1252`, and the one that succeeds has `charset=UTF-8`.

Fails:
```
...
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="------------F2C3840841699E1CBA46489D"

This is a multi-part message in MIME format.
--------------F2C3840841699E1CBA46489D
Content-Type: text/plain; charset=windows-1252
Content-Transfer-Encoding: 8bit

some text

--------------F2C3840841699E1CBA46489D
Content-Type: text/html; charset=windows-1252
Content-Transfer-Encoding: 8bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=windows-1252">
  </head>
  <body bgcolor="#FFFFFF" text="#000000">
    <p><font face="Helvetica, Arial, sans-serif">no sign</font><br>
    </p>
    <br>
    <div class="moz-signature">-- <br>
      <br>
      <b>John Doe</b><br>
      <a href="https://example.com">Example</a><br>
    </div>
  </body>
</html>

--------------F2C3840841699E1CBA46489D--
```

Doesn't fail:

```
...
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary=94eb2c18fe78175025054b289093

--94eb2c18fe78175025054b289093
Content-Type: text/plain; charset=UTF-8

Hello

--94eb2c18fe78175025054b289093
Content-Type: text/html; charset=UTF-8

<div dir="auto">Hello</div>

--94eb2c18fe78175025054b289093--
```

**Comment by ramirogm** [comment]
Hi, I'm getting the same error if I send an email with this From header:
From:  
 =?utf-8?Q?=22Equipo=20de=20Aplic=2Ede=20Gestion=22?= <teambi@snoop.com.ar>

If I change it to:
From:  
 TeamBI <teambi@snoop.com.ar>

I get NO error.

Any idea what's going on here? I'm forwarding an email and the encoding is right ( per http://dogmamix.com/MimeHeadersDecoder/ )

**Comment by ramirogm** [comment]
Found there's a problem with the `processMessage` function, it changes the `From:` to something illegal like:
`From:  <HIDDENXXX@snoop.com.ar>\r\n =?utf-8?Q?=22Equipo=20de=20Aplic=2Ede=20Gestion=22?= <teambi@snoop.com.ar>\r\n`

So there you have two addresses in the From Header.

I can't debug it right now, but there seems to be a problem with the RegEx.

**Comment by deathemperor** [comment]
I'm late to the party but I had to use punycode (nodejs: https://github.com/mathiasbynens/punycode.js) to encode the name first otherwise AWS will shout `"InvalidParameterValue: Extra route-addr"`

**Comment by tom-exacc** [comment]
I'm even later to the party. My issue was resolved by changing from await client.SendEmailAsync(request) to client.SendEmailAsync(request).Result - not sure why, I pray it keeps delivering.
