### ISSUE TITLE
original mail header sent in body of messages

### ISSUE THREAD

**Issue by ctr49** [arithmetric/aws-lambda-ses-forwarder#6]
When I send an e-mail to an assigned address it gets forwarded now (after the Return-Path merge), but all original email header is put into the body of the forwarded mail, so it also loses all properties like subject and message ID.

Any idea what might be causing this? I can forward an example if needed.

**Comment by arithmetric** [comment]
@ctr49 I pushed an change to fix how Return-Path (and Reply-To) are altered. I think this will fix the headers issue.

**Comment by stcruy** [comment]
It did! Thanks :)
