### ISSUE TITLE
1 Mail getting redirected (sent) ~5 times

### ISSUE THREAD

**Issue by jameel263** [arithmetric/aws-lambda-ses-forwarder#61]
I've come across a weird situation where occasionally when an email is sent to the domain where I have the redirect set up, the redirected to domain gets five identical copies of the email.

It looks like lambda is fired off five times one after another but the execution of the lambdas still occur in parallel. I.e. the lambda doesn't happen back to back but all at once.

Has anyone else come across this problem before? I'm still in the process of debugging the cause so any help would be appreciated.

**Comment by jameel263** [comment]
I found the issue. I was creating multiple SES rules to make it easy to add domains to another ses rule when one hits the limit (only 100 recipients are allowed per rule).

Some of these rules were empty and SES apparently treats them as a catch all causing multiple lambdas to be fired in a short period of time. 

So unrelated to the ses forwarder. :)

**Comment by jakubboucek** [comment]
Hi, SES rules are matched in order and all matches are fired.
If you want to stop processing following matching rules, you must add [Stop action](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-action-stop.html).

Is highly recommended to set recipients in Rules for prevent unpredictable behavior.

Read more at: [SES Email-Receiving Concepts](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-concepts.html)
