### ISSUE TITLE
Unable to import module 'index'

### ISSUE THREAD

**Issue by Suncatcher** [arithmetric/aws-lambda-ses-forwarder#66]
In Lambda function logs I see:

    START RequestId: 12ea793b-9ef2-11e7-b1ef-b360a5b0eab4 Version: $LATEST
    Unable to import module 'index': Error at Module.require (module.js:353:17)
    END RequestId: 12ea793b-9ef2-11e7-b1ef-b360a5b0eab4
    REPORT RequestId: 12ea793b-9ef2-11e7-b1ef-b360a5b0eab4	Duration: 1.88 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 21 MB

What does it mean?

**Comment by Suncatcher** [comment]
Resolved. Function was imported incorrectly.

**Comment by evilplanet** [comment]
@Suncatcher Could you tell me how you resolved it? What was causing it? I'm having the same issue.

**Comment by Suncatcher** [comment]
@evilplanet try to reimport the full lambda package with all the external files and libraries. That helped me.

**Comment by evilplanet** [comment]
My problem was a lack of permissions. I changed the permissions to 777, then it worked.
