### ISSUE TITLE
level: 'error', message: 'Step returned error: Error: Received invalid SES message.'

### ISSUE THREAD

**Issue by marquix** [arithmetric/aws-lambda-ses-forwarder#69]
Hi Guys,

I´ve spent a few hours double checking 99% of the settings according to setup yet I still cannot get over this error message.  Any tips?

{ level: 'error',
message: 'Step returned error: Error: Received invalid SES message.',
error: [Error: Error: Received invalid SES message.],
stack: 'Error: Error: Received invalid SES message.\n at exports.parseEvent (/var/task/index.js:59:27)' }

 level: 'error',
message: 'Step returned error: Error: Could not make readable copy of email.',
error: [Error: Error: Could not make readable copy of email.],
stack: 'Error: Error: Could not make readable copy of email.\n at Response.<anonymous> (/var/task/index.js:144:11)\n at Request.<anonymous>

**Comment by capawaky** [comment]
Hi, mind letting us know what solved your issue? :)

**Comment by marquix** [comment]
Sure.  Apparently the Guide states that the Lambda role should include our S3 bucket name.  This seems to cause an issue.  I had to omit the name so that the Role Code looks like this:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": "ses:SendRawEmail",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::*"
        }
    ]
}`
