### ISSUE TITLE
PR for domainMapping?

### ISSUE THREAD

**Issue by SocalNick** [arithmetric/aws-lambda-ses-forwarder#72]
Would you support a PR to add a domain mapping feature to forward all mail from one domain to another with the same username? Configuration might be like:

```
{
    config: {
      fromEmail: "noreply@example.com",
      emailBucket: "s3-bucket-name",
      emailKeyPrefix: "emailsPrefix/",
      forwardMapping: {
        "info@example.com": [
          "example.john@example.com",
          "example.jen@example.com"
        ],
        "abuse@example.com": [
          "example.jim@example.com"
        ]
      },
      domainMapping: {
        "@foo.example.com": "@example.com"
      }
    }
  }
```

So `anyuser@foo.example.com` would forward to `anyuser@example.com`. The forwardMapping would still take precedent, but if there aren't any matches for forwardMapping, it would check the domainMapping.

Thoughts?

I've currently done this by overriding the transformRecipients function in my own module, but it's not as succinct as it would be integrated directly. I'm happy to provide tests, implementation, and documentation.

Thanks!

Nick

**Comment by quaeritate** [comment]
Did you fork this project to make your change? I can't find a copy under your account. I was about to write something like this and would rather build on something someone else has already done.

**Comment by SocalNick** [comment]
Sorry, I never ended up using this.
