### ISSUE TITLE
Node.js version deprecated

### ISSUE THREAD

**Issue by Suncatcher** [arithmetric/aws-lambda-ses-forwarder#83]
Recently I received this message from Amazon denoting that the version of Node.js used with the forwarder is deprecated. I just 

> Hello,
> 
> Your AWS Account currently has one or more Lambda functions configured to use the Node.js v4.3 runtime. The Node Foundation declared End-of-Life (EOL) for Node.js v4 on April 30, 2018. As a result, this version of Node.js is no longer receiving bug fixes, security updates, or performance improvements from the Node Foundation. Per the AWS Lambda runtime support policy [2] , language runtimes that have been end-of-lifed by the supplier are deprecated in AWS Lambda. While invocations of Lambda functions configured to use Node.js v4.3 will continue to work normally, the ability to create new Lambda functions configured to use the Node.js v4.3 runtime will be disabled on July 31, 2018. Code updates to existing functions using Node.js v4.3 will be disabled on October 31, 2018. We strongly encourage you to update all your functions to a newer version of Node.js (v6.10 or v8.10) so that you continue to benefit from important security, performance, and functionality enhancements offered by the Node Foundation via more recent releases.
> 
> Which version of Node.js should I migrate to?
> 
> While Node.js v6.10 is available on AWS Lambda, we recommend that you migrate directly to Node.js v8.10, a newer version with improved ES6 support and other language and API improvements. The AWS Lambda programming model for Node.js v8.10 maintains backwards compatibility with previous versions to simplify portability. We recommend that you test your Lambda function to validate its behavior on the newer version of Node.js.

I just changed the Node.js version to 8.1 in the function config and all went fine, I assume that it's gonna be done in repo too.

**Comment by arithmetric** [comment]
@Suncatcher Thanks for the report. I've updated the documentation to recommend using Node.js v6.10 or v8.10.
