### ISSUE TITLE
'Reply-To address not added because From address was not properly extracted.'

### ISSUE THREAD

**Issue by nelusuciu-coera** [arithmetric/aws-lambda-ses-forwarder#86]
In some cases the email that is parsed contains
"From:<user@example.com>"
In these cases the extraction of the From: does not work because the regular expression expects a space after :
In my project I fixed that by removing the space after From:  in the regular expression in lines 190 and 205. 

https://github.com/arithmetric/aws-lambda-ses-forwarder/blob/a04bf17228f4ee88721d9c7fd22413045cf0909c/index.js#L190

**Comment by ccjmne** [comment]
Apparently, you're correct and the [RFC 5322 – Internet Message Format](https://www.rfc-editor.org/rfc/rfc6854.txt) (it is the most recent one) specifies that this space, immediately following the colon in the header fields, is merely **allowed**, not mandatory:

> 2.2.  Header Fields
> 
>    Header fields are lines **beginning with a field name, followed by a
>    colon (":"), followed by a field body, and terminated by CRLF**.  A
>    field name MUST be composed of printable US-ASCII characters (i.e.,
>    characters that have values between 33 and 126, inclusive), except
>    colon.  A field body may be composed of printable US-ASCII characters
>    as well as the space (SP, ASCII value 32) and horizontal tab (HTAB,
>    ASCII value 9) characters (together known as the white space
>    characters, WSP).  A field body MUST NOT include CR and LF except
>    when used in "folding" and "unfolding", as described in section
>    2.2.3.  All field bodies MUST conform to the syntax described in
>    sections 3 and 4 of this specification.
> 
>    [...]
> 
> 2.2.2.  Structured Header Field Bodies
> 
>    Some field bodies in this specification have a syntax that is more
>    restrictive than the unstructured field bodies described above.
>    These are referred to as "structured" field bodies.  Structured field
>    bodies are sequences of specific lexical tokens as described in
>    sections 3 and 4 of this specification.  Many of these tokens **are
>    allowed [...] to be introduced or end with [...] the white space
>    characters**, and those white space characters are subject to "folding"
>    and "unfolding" as described in section 2.2.3.  Semantic analysis of
>    structured field bodies is given along with their syntax.

(NB: emphasis & ellipses are mine)

**Comment by ccjmne** [comment]
Since I'm at it, it appears that "From" (as any other defined header field, AFAICT) **doesn't have to** start with an uppercase "F", if we refer to section 1.2.2 of the same RFC:

> 1.1.2.  Syntactic Notation
> 
>    This specification uses the Augmented Backus-Naur Form (ABNF)
>    [RFC5234] notation for the formal definitions of the syntax of
>    messages.  Characters will be specified either by a decimal value
>    (e.g., the value %d65 for uppercase A and %d97 for lowercase A) or **by
>    a case-insensitive literal value enclosed in quotation marks (e.g.,
>    "A" for either uppercase or lowercase A)**.

(NB: emphasis is mine)

Thus, I suggest the header-maching regular expressions use the `i` flag.

--

Also, it appears that **`/n` cannot exist without `/r`**, at least not to delimit headers or "folding" of header bodies:

> 2.1. General Description
>    
>   [...]
> 
>    Messages are divided into lines of characters.  A line is a series of
>    characters that is delimited with the two characters carriage-return
>    and line-feed; that is, **the carriage return (CR) character (ASCII
>    value 13) followed immediately by the line feed (LF) character (ASCII
>    value 10)**.  (The carriage return/line feed pair is usually written in
>    this document as "CRLF".)

(NB: emphasis & ellipsis are mine)

... But I'd rather be too lenient there than too restrictive 🙂
