### ISSUE TITLE
forwardMapping wildcards ?

### ISSUE THREAD

**Issue by marcelomagf** [arithmetric/aws-lambda-ses-forwarder#90]
would like to setup a _"catch all"_ , so guess I need something like:

```
forwardMapping: {
        "*": [
          "tome@example.com"
        ]
```

Any chance I get this working?

**Comment by 3boysdad** [comment]
pretty sure the catch all exists already...

"@<a domain>": [
      "noone@home.com"
    ]

Mind you it'll be on a per domain, which I think far more flexible despite the need to create one entry per domain.

**Comment by marcelomagf** [comment]
Indeed! Thanks. Should have tried it..

**Comment by arithmetric** [comment]
In version 5.0.0, there is support for a wildcard/catch all for email to any address/any domain.

See:
- #77 
- https://github.com/arithmetric/aws-lambda-ses-forwarder/blob/v5.0.0/index.js#L37
